travis:
  secure:
    BINSTAR_TOKEN: Om59AES4atQSFO8oTVX725WyhWBny27O+Kem4aO9BDLyo1dOuEJo2tPCUhVZf4pItMoSPmQVGvGWT1vdL2zg3o2nbHedZbazIrHttdmceEyfQyRz/TIZYmom+fhT9UnKWOMYxtnWkhZNt1IDitmTMJLKaN7JXbBYclAW8AkyCjFuSt1AnP7XHJhpLGbzLb844lP070oOERCefzX9rH6SWuymhcMFjKWfnb6zNncEcrg5YjeLbjuP2Mr2EjmuJJsWmVLW2GxlHXX415bs+wk81l4UdswrOM6F423qkTa62YepBAZ79mh74vR4bazWbnpgShUqh19xn9UXRsYm4xXwdy0nWwUHEy3zShEtTUoPRFvG4ZlQ0hRN4yXHKZbPqF3hfkrpeMSh5IU3Eg8ZKUhuuVPv/n3A06PK0s5YP8+2eEHUK3ihbpwiEwh1RrBUFeqpGJtNnZyITgKyBuidBCDcX6jZcDLNwzleE/STzl6qcpz+qjlkaqyl4EWF8uZ/KFHSycFTK67SIwfmzI3w0ocJaA4OB1XxvD1jT8sN8HOtk8xli/q8OhhmOufwo67uiAf7ts63xOP64lacTGfKsSNE3IZO/c63C4DotVRRslkns89W58pw/RzzgjssHPLe4xQLONMGPyrGRl1Qd3gTXIeUbkyyVq2dn/3LHwoBmVaX8m0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
